name: helm-tar-update
description: Buildkite plugin to automatically fetch helm tarballs
author: Equinix Metal
requirements:
  - bash
  - helm
  - git
configuration:
  properties:
    helm_token:
      type: string
    helm_user:
      type: string
    helm_registry:
      type: string